# Test Configuration for Model Testing
# This YAML file contains all necessary parameters for testing the models

# Basic settings
seed: 250104
device: 'cpu'
experiment_name: 'dev'

# Data paths
data_root: '/Users/eunsupark/ap_project/data/dataset'
save_root: '/Users/eunsupark/ap_project/results'
stat_file_path: '/Users/eunsupark/ap_project/data/statistics.pkl'
train_list_path: '/Users/eunsupark/ap_project/data/train_list.csv'
test_list_path: '/Users/eunsupark/ap_project/data/test_list.csv'

# Model architecture
## Linear Model
input_variables:
  - 'Bx_GSE'
  - 'By_GSM'
  - 'Bz_GSM'
  - 'B_magnitude'
  - 'Flow_speed'
  - 'Proton_density'
  - 'Temperature'
  - 'Kp_index'
  - 'ap_index'
  - 'DST_index'
  - 'R_sunspot'
input_sequence_length: 40
target_variables:
  - 'ap_index'
target_sequence_length: 24
num_linear_output: 256

## Inception-LSTM Model
inception_in_channels: 2
inception_out_channels: 96
inception_in_image_size: 64
inception_in_image_frames: 20
lstm_hidden_size: 512

# Training settings
batch_size: 8
num_workers: 0
phase: 'train'
num_epochs: 10

# Optimization
learning_rate: 0.0002

# Logging and saving
report_freq: 100
save_freq: 1
test_freq: 1
