batch_size: 4
data_root: /Users/eunsupark/ap_project/data/dataset
device: cuda
experiment_name: wulver_huber_multi_criteria
inception_in_channels: 2
inception_in_image_frames: 20
inception_in_image_size: 64
inception_out_channels: 96
input_sequence_length: 40
input_variables:
- Bx_GSE
- By_GSM
- Bz_GSM
- B_magnitude
- Flow_speed
- Proton_density
- Temperature
- Kp_index
- ap_index
- DST_index
- R_sunspot
learning_rate: 0.0002
loss_type: huber_multi_criteria
lstm_hidden_size: 512
model_save_freq: 10
num_epochs: 100
num_linear_output: 256
num_workers: 0
phase: train
report_freq: 1000
save_root: /Volumes/work/Ap/results
seed: 250104
stat_file_path: /Users/eunsupark/ap_project/data/statistics.pkl
target_sequence_length: 24
target_variables:
- ap_index
train_list_path: /Users/eunsupark/ap_project/data/train_list.csv
validation_list_path: /Users/eunsupark/ap_project/data/validation_list.csv
