experiment_name: 'dev'

# Data Paths
data_root: '/Users/eunsupark/ap_project/data/datasets' 

# Input/Output Settings
input_variables:
  - 'Bx_GSE'
  - 'By_GSM'
  - 'Bz_GSM'
  - 'B_magnitude'
  - 'Flow_speed'
  - 'Proton_density'
  - 'Temperature'
  - 'Kp_index'
  - 'ap_index'
  - 'DST_index'
  - 'f107_index'
  - 'R_sunspot'
target_variables:
  - 'ap_index'
