"""HDF5 file viewer for solar observation datasets.

Simple script to inspect the contents of HDF5 files generated by
01_get_data_from_database.py (original) and 02_merge_and_resize.py (merged).
"""

import sys
import h5py
import numpy as np


def view_h5(filepath: str) -> None:
    """Displays the structure and contents of an HDF5 file.

    Args:
        filepath: Path to the HDF5 file.
    """
    print(f"\n{'='*60}")
    print(f"File: {filepath}")
    print('='*60)

    with h5py.File(filepath, 'r') as f:
        # File attributes
        print("\n[Attributes]")
        for key, value in f.attrs.items():
            print(f"  {key}: {value}")

        # OMNI group
        if 'omni' in f:
            print("\n[OMNI]")
            omni = f['omni']

            # Merged format (data + columns)
            if 'data' in omni:
                data = omni['data'][:]
                print(f"  data shape: {data.shape}")
                print(f"  data dtype: {data.dtype}")
                if 'columns' in omni:
                    columns = [c.decode() if isinstance(c, bytes) else c
                               for c in omni['columns'][:]]
                    print(f"  columns ({len(columns)}): {columns[:5]}...")
                print(f"  sample values (first row): {data[0][:5]}...")

            # Original format (individual datasets)
            else:
                for key in list(omni.keys())[:10]:
                    value = omni[key][()]
                    print(f"  {key}: {value}")
                if len(omni.keys()) > 10:
                    print(f"  ... and {len(omni.keys()) - 10} more")

        # SDO group
        if 'sdo' in f:
            print("\n[SDO]")
            for channel in f['sdo'].keys():
                data = f['sdo'][channel][:]
                print(f"  {channel}:")
                print(f"    shape: {data.shape}")
                print(f"    dtype: {data.dtype}")
                print(f"    min/max: {data.min()}/{data.max()}")

    print()


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python view_h5.py <file.h5> [file2.h5 ...]")
        print("\nExamples:")
        print("  python view_h5.py /Volumes/AP-PROJECT/datasets/original/2010090800.h5")
        print("  python view_h5.py /Volumes/AP-PROJECT/datasets/merged/2010090800.h5")
        sys.exit(1)

    for filepath in sys.argv[1:]:
        view_h5(filepath)
