# Enhanced Multi-Modal Model Configuration
# Configuration for transformer + ConvLSTM + CrossModalFusion architecture

# Basic Settings
seed: 250104
device: 'cuda'  # 'cuda', 'cpu', or 'mps'
experiment_name: 'wulver_mm_base'

# Data Paths
data_root: '/mmfs1/home/hl545/ap/data/dataset'
save_root: '/mmfs1/home/hl545/ap/results'
stat_file_path: '/mmfs1/home/hl545/ap/data/statistics.pkl'
train_list_path: '/mmfs1/home/hl545/ap/data/train_list.csv'
validation_list_path: '/mmfs1/home/hl545/ap/data/validation_list.csv'

# Input/Output Settings
input_variables:
  - 'Bx_GSE'
  - 'By_GSM'
  - 'Bz_GSM'
  - 'B_magnitude'
  - 'Flow_speed'
  - 'Proton_density'
  - 'Temperature'
  - 'Kp_index'
  - 'ap_index'
  - 'DST_index'
  - 'R_sunspot'
input_sequence_length: 40
target_variables:
  - 'ap_index'
target_sequence_length: 24

# Transformer Model Settings
transformer_d_model: 256
transformer_nhead: 8
transformer_num_layers: 3
transformer_dim_feedforward: 512
transformer_dropout: 0.1

# ConvLSTM Model Settings
convlstm_input_channels: 2
convlstm_hidden_channels: 64
convlstm_kernel_size: 3
convlstm_num_layers: 2

# Cross-Modal Fusion Settings
fusion_num_heads: 4
fusion_dropout: 0.1

# Image Settings
image_size: 64

# Training Settings
batch_size: 4
num_workers: 0
phase: 'train'
num_epochs: 100

# Optimization
loss_type: 'mse'
learning_rate: 0.0002

# Logging and Saving
report_freq: 1000
model_save_freq: 10